> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rubabaa499/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/rubabaa499/numpy-array-operations


'https://jovian.com/rubabaa499/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.zeros  # (change this)
function2 = np.arange
function3 = np.random.rand
function4 = np.reshape
function5 = np.linspace

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [6]:
# Example 1 - working (change this)
import numpy as np

# Create a 1D array of length 5 filled with zeros
array_1d = np.zeros(5)
print(array_1d)


[0. 0. 0. 0. 0.]


Explanation about example:  This line creates a 1D NumPy array of length 5 filled with zeros. The np.zeros() function takes a single argument, which is the shape of the array. In this case, we pass the integer value 5, indicating that we want a 1D array with 5 elements.Then I printed the array.

In [7]:
# Example 2 - working
import numpy as np

# Create a 3D array with shape (2, 3, 4) filled with zeros
array_3d = np.zeros((2, 3, 4))
print(array_3d)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


Explanation about example:This line creates a 3D NumPy array with a shape of (2, 3, 4) filled with zeros. The np.zeros() function takes a tuple as its argument, which represents the shape of the array. In this case, we pass the tuple (2, 3, 4), which indicates that we want a 3D array with 2 "layers", 3 rows in each layer, and 4 columns in each row.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np

# Create a 3D array with shape (2, 3, 4) filled with zeros
array_3d = np.zeros(2, 3, 4) 
print(array_3d)


TypeError: Cannot interpret '3' as a data type

Explanation about example (why it breaks and how to fix it): It is giving a type error. The error occurs because we've incorrectly passed separate arguments to np.zeros() instead of a tuple for the shape. The correct way to define the shape as (2, 3, 4) is by using a tuple as shown in the original code. In the erroneous code, the interpreter interprets the values 2, 3, and 4 as separate arguments, leading to a "TypeError" as it expects a single argument representing the shape of the array.

Some closing comments about when to use this function. we can use this funciton to print zeros in matrix.

In [9]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rubabaa499/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/rubabaa499/numpy-array-operations


'https://jovian.com/rubabaa499/numpy-array-operations'

## Function 2 - ???

Add some explanations

In [12]:
# Example 1 - working


# Create an array with values from 0 to 9 
arr1 = np.arange(0, 10, 2)
print(arr1)


[0 2 4 6 8]


Explanation about example: In this example, the np.arange() function generates an array starting from 0, up to (but not including) 10, with a step size of 2. It includes 0, 2, 4, 6, and 8 in the resulting array.

In [13]:
# Example 2 - working

# Create an array with values from 10 to 1
range_array_2 = np.arange(10, 0, -1)
print(range_array_2)


[10  9  8  7  6  5  4  3  2  1]


Explanation about example:In this example, the np.arange() function generates an array starting from 10 and counting down to (but not including) 0, with a step size of -1. The resulting array contains elements in reverse order from 10 to 1

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np

# Create an array with values from 10 to 1
range_array_2 = np.arange(10, 0, -1, 2)  # Incorrect, the step size should be -1
print(range_array_2)


TypeError: Cannot interpret '2' as a data type

Explanation about example (why it breaks and how to fix it):In this code, we get an error by specifying a step size of 2 instead of -1 in the np.arange() function call. The error occurs because the step size must be a non-zero number, but we provided 2 as the step, which is incorrect for creating a reversed range from 10 to 1. The correct step value for a descending range should be -1 to generate the desired output

Some closing comments about when to use this function.

In [15]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rubabaa499/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/rubabaa499/numpy-array-operations


'https://jovian.com/rubabaa499/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [16]:
# Example 1 - working
arr1 = np.random.rand(10)
print(arr1)

[0.42483419 0.75446874 0.04527385 0.51225609 0.50544567 0.05682453
 0.45449008 0.24221236 0.3178449  0.52347209]


Explanation about example: This line generates a 1D NumPy array arr1 with a length of 10 filled with random numbers from a uniform distribution in the half-open interval [0.0, 1.0). The np.random.rand() function takes a single argument, which specifies the size (or shape) of the random array to be created. In this case, we pass the value 10, indicating that we want an array of length 10.

In [18]:
# Example 2 - working

# Create a large 2D array of shape (100, 100) with random numbers
arr1 = np.random.rand(100, 100)
print(arr1)


[[0.78410822 0.23983232 0.2228339  ... 0.92678108 0.19692955 0.99712056]
 [0.33702288 0.14561389 0.26519934 ... 0.13587195 0.98524592 0.85683158]
 [0.47960475 0.68049611 0.62222457 ... 0.28185324 0.14555767 0.95393901]
 ...
 [0.98944171 0.69593615 0.94106704 ... 0.66960209 0.12481851 0.15821579]
 [0.02498365 0.77365964 0.6067666  ... 0.11061826 0.12281712 0.68391682]
 [0.71605666 0.01719996 0.98923012 ... 0.25197453 0.62812997 0.5476076 ]]


Explanation about example: This line creates a 2D NumPy array named arr1 with a shape of (100, 100) filled with random numbers. The np.random.rand() function generates random numbers from a uniform distribution in the half-open interval [0.0, 1.0). The function takes two arguments, specifying the shape of the array to be created. In this case, we pass (100, 100) to indicate that we want a 2D array with 100 rows and 100 columns.

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np

# Create a large 2D array of shape (100, 100) with random numbers
array = np.random.rand((100, 100, 100))  
print(array)


TypeError: 'tuple' object cannot be interpreted as an integer

Explanation about example (why it breaks and how to fix it):The error occurs because the argument passed to np.random.rand() should be the shape of the array, specified as integers or a tuple of integers. In the provided code, an extra set of parentheses is used around (100, 100, 100), which causes the error. 
By removing the extra parentheses, the code correctly creates a 2D NumPy array of shape (100, 100) filled with random numbers, and it will work without errors.

Some closing comments about when to use this function.

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rubabaa499/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/rubabaa499/numpy-array-operations


'https://jovian.com/rubabaa499/numpy-array-operations'

## Function 4 - ???

Add some explanations

In [24]:
# Example 1 - working
import numpy as np

# Create a 1D array with 12 elements
original_array = np.arange(12)

# Reshape the 1D array into a 2D array of shape (3, 4)
reshaped_array = np.reshape(original_array, (3, 4))

print("Original Array:")
print(original_array)
print("Reshaped Array:")
print(reshaped_array)


Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Explanation about example: In this example, we create a 1D array with 12 elements using np.arange(12). Then, we use np.reshape() to convert the 1D array into a 2D array with a shape of (3, 4). The elements from the original array are filled into the new 2D array row by row.

In [25]:
# Example 2 - working

# Create a 1D array with 27 elements
original_array = np.arange(27)

# Reshape the 1D array into a 3D array of shape (3, 3, 3)
reshaped_array = np.reshape(original_array, (3, 3, 3))

print("Original Array:")
print(original_array)
print("Reshaped Array:")
print(reshaped_array)


Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
Reshaped Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Explanation about example: In this example, we create a 1D array with 27 elements using np.arange(27). Then, we use np.reshape() to convert the 1D array into a 3D array with a shape of (3, 3, 3). The elements from the original array are distributed across the new 3D array in a contiguous manner.

In [26]:
# Example 3 - breaking (to illustrate when it breaks)

# Create a 1D array with 27 elements
original_array = np.arange(27)

# Reshape the 1D array into a 3D array of shape (3, 3, 3)
reshaped_array = np.reshape(original_array, (3, 3, 4))  # Incorrect shape for 3D array

print("Original Array:")
print(original_array)
print("Reshaped Array:")
print(reshaped_array)


ValueError: cannot reshape array of size 27 into shape (3,3,4)

Explanation about example (why it breaks and how to fix it): In this modified code, we've introduced an error by specifying the shape as (3, 3, 4) in the np.reshape() function. The error occurs because the total number of elements in the original 1D array (27) does not match the required number of elements for the desired 3D array shape (3, 3, 4), which should be 3 x 3 x 4 = 36.

To create a 3D array with shape (3, 3, 3) from the original 1D array with 27 elements, the correct shape should be specified as (3, 3, 3), which matches the number of elements in the original array.

Some closing comments about when to use this function.

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rubabaa499/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/rubabaa499/numpy-array-operations


'https://jovian.com/rubabaa499/numpy-array-operations'

## Function 5 - ???

Add some explanations

In [28]:
# Example 1 - working

# Create an array of 6 evenly spaced values from 0 to 10 (inclusive)
linspace_array_1d = np.linspace(0, 10, 6)
print(linspace_array_1d)


[ 0.  2.  4.  6.  8. 10.]


Explanation about example:In this example, np.linspace(0, 10, 6) creates an array with six evenly spaced values ranging from 0 to 10, inclusive. The function divides the interval [0, 10] into six equal parts, and it includes the starting and ending points.

In [30]:
# Example 2 - working

# Create a 2D array of shape (3, 4) with evenly spaced values from 5 to 15 (inclusive)
linspace_array_2d = np.linspace(5, 15, 12).reshape((3, 4))
print(linspace_array_2d)



[[ 5.          5.90909091  6.81818182  7.72727273]
 [ 8.63636364  9.54545455 10.45454545 11.36363636]
 [12.27272727 13.18181818 14.09090909 15.        ]]


Explanation about example: In this example, np.linspace(5, 15, 12) creates an array with 12 evenly spaced values ranging from 5 to 15, inclusive. We then reshape this 1D array into a 2D array of shape (3, 4). The function divides the interval [5, 15] into 12 equal parts and includes the starting and ending points in the array.

In [31]:
# Example 3 - breaking (to illustrate when it breaks)

# Create an array of 6 evenly spaced values from 0 to 10 (inclusive)
linspace_array_1d = np.linspace(0, 10, -6)  # Incorrect, the number of samples cannot be negative
print(linspace_array_1d)


ValueError: Number of samples, -6, must be non-negative.

Explanation about example (why it breaks and how to fix it): In this modified code, we've introduced an error by specifying a negative value, -6, as the number of samples in the np.linspace() function. The error occurs because the number of samples must be non-negative; that is, it should be greater than or equal to zero. By providing a valid number of samples (6) in np.linspace(0, 10, 6), the code generates an array with six evenly spaced values ranging from 0 to 10, inclusive.

Some closing comments about when to use this function.

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rubabaa499/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/rubabaa499/numpy-array-operations


'https://jovian.com/rubabaa499/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [33]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rubabaa499/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/rubabaa499/numpy-array-operations


'https://jovian.com/rubabaa499/numpy-array-operations'